### ISSUE TITLE
Default Install Error on coffeeshop

### ISSUE THREAD

**Issue by readoc** [Apress/Secure-Web-Application-Development#1]
The default vagrant install results in a coffeeshop error when accessing the main site via a Web browser. All other default sites work.

AttributeError at /
module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
Request Method:	GET
Request URL:	http://10.50.0.2/
Django Version:	3.2.7
Exception Type:	AttributeError
Exception Value:	
module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
Exception Location:	/usr/lib/python3/dist-packages/OpenSSL/crypto.py, line 1573, in X509StoreFlags
Python Executable:	/usr/bin/python3
Python Version:	3.8.10
Python Path:	
['/var/www/coffeeshopsite',
 '/var/www',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '/usr/local/lib/python3.8/dist-packages',
 '/usr/lib/python3/dist-packages']

**Comment by mbakereth** [comment]
Hi,

Thanks for this.  The default pip3 version for that Ubuntu release appears to have developed a disagreement with pyOpenSSL.  Try pulling again, destroying your vagrant machine with vagrant destroy, then rebuilding again with vagrant up.  It should work now

**Comment by mbakereth** [comment]
Hi.  I didn't hear back so I assume it is ok now, so closing.
